version: '3.9'

services:
  ms-article-postgres:
    container_name: rentsoft_ms_article_postgres
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB},${POSTGRES_DB_TEST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASSWORD}
      ALLOW_IP_RANGE: 0.0.0.0/0
      MAINTAINANCE_WORK_MEM: 512MB
    volumes:
      - $PWD/./docker/postgres/data:/var/lib/postgresql:rw
#      - $PWD/./docker/postgres/postgresql.conf:/etc/postgresql/11/main/postgresql.conf
#    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      test: su -m postgres -c " pg_isready -U postgres -d article"
      interval: 10s
      timeout: 5s
      retries: 5

  ms-article-php:
    container_name: rentsoft_ms_article_php
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    depends_on:
      - ms-article-postgres
    volumes:
      - ./api/:/var/www/

  ms-article-nginx:
    container_name: rentsoft_ms_article_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile-api
    environment:
      VIRTUAL_HOST: ${PHP_HOST}
      HTTPS_METHOD: noredirect
#      LETSENCRYPT_HOST: ${PHP_HOST}
#      LETSENCRYPT_EMAIL: info@${PHP_HOST}
    volumes:
      - ./api/:/var/www/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/api.conf:/etc/nginx/sites-available/default.conf
      - ./docker/nginx/conf.d/api.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs/api:/var/log
    depends_on:
      - ms-article-php

networks:
  default:
    external: true
    name: nginx-proxy
