security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        #        users_in_memory: { memory: null }
        oauth:
            id: knpu.oauth2.user_provider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: oauth
            custom_authenticators:
                - App\Security\KeycloakAuthenticator
            logout: ~

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
       - { path: ^/_profiler, roles: [PUBLIC_ACCESS] }
       - { path: ^/sync, roles: [PUBLIC_ACCESS] }
       - { path: ^/docs, roles: [PUBLIC_ACCESS] }
       - { path: ^/health, roles: [PUBLIC_ACCESS] }
       - { path: ^/oauth, roles: [PUBLIC_ACCESS] }
       - { path: ^/, roles: [IS_AUTHENTICATED_FULLY] }
#        - { path: ^/docs, roles: [PUBLIC_ACCESS, IS_AUTHENTICATED_FULLY, IS_ANONYMOUS] }
#        - { path: ^/_profiler, roles: [PUBLIC_ACCESS, IS_AUTHENTICATED_FULLY, IS_ANONYMOUS] }
#        - { path: ^/open, roles: [PUBLIC_ACCESS, IS_AUTHENTICATED_FULLY, IS_ANONYMOUS] }
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
