<?php

declare(strict_types=1);

namespace App\Entity;

use App\Entity\Client\Permission;

abstract class AbstractEntity
{
    CONST STATUS_NEW = 1;
    CONST STATUS_ACTIVE = 10;
    CONST STATUS_INACTIVE = 20;
    CONST STATUSES = [self::STATUS_NEW, self::STATUS_ACTIVE, self::STATUS_INACTIVE];

    CONST DEFAULT_PRICE_CALCULATION_FIX = 10;
    CONST DEFAULT_PRICE_CALCULATION_RATES_DAY = 20;
    CONST DEFAULT_PRICE_CALCULATION_RATES_DAY_FIX = 21;
    CONST DEFAULT_PRICE_CALCULATION_RATES_HOUR = 30;

    CONST DEFAULT_PRICE_CALCULATION_TYPE_PER_DAY = 10;
    CONST DEFAULT_PRICE_CALCULATION_TYPE_PER_NIGHT = 20;

    CONST PRICE_RATE_TYPE_PER_UNIT = 10;
    CONST PRICE_RATE_TYPE_FIX = 20;

    CONST ARTICLE_TYPE_CAR = "car";
    CONST ARTICLE_TYPE_CARAVAN = "caravan";
    CONST ARTICLE_TYPE_MACHINE = "machine";
    CONST ARTICLE_TYPE_ARTICLE = "article";
    CONST ARTICLE_TYPE_KM_PACKAGE = "km_package";

    CONST ARTICLE_USE_FOR_NONE = 0;
    CONST ARTICLE_USE_FOR_RENTAL = 10;
    CONST ARTICLE_USE_FOR_SELL = 20;
    CONST ARTICLE_USE_FOR_OWN = 30;
    CONST ARTICLE_USE_FOR_DISPLAY = 40;

    CONST ARTICLE_COUNTER_KM = "km";
    CONST ARTICLE_COUNTER_HOUR = "hour";

    CONST QUANTITY_MANUAL = 10;
    CONST QUANTITY_STOCK = 20;

    CONST ROLE_OWNER = "ROLE_OWNER";
    CONST ROLE_USER = "ROLE_USER";
    CONST ROLE_ADMIN = "ROLE_ADMIN";
    CONST ROLE_SERVICE = "ROLE_SERVICE";
    CONST ROLES = [self::ROLE_OWNER, self::ROLE_USER, self::ROLE_ADMIN, self::ROLE_SERVICE];

    CONST PERMISSION_CREATE = "CREATE";
    CONST PERMISSION_READ = "READ";
    CONST PERMISSION_UPDATE = "UPDATE";
    CONST PERMISSION_DELETE = "DELETE";
    CONST PERMISSION_COLLECTION_ = "COLLECTION_";
    CONST PERMISSIONS = [self::PERMISSION_CREATE, self::PERMISSION_READ, self::PERMISSION_UPDATE, self::PERMISSION_DELETE, self::PERMISSION_COLLECTION_ . self::PERMISSION_READ];

}
